name: Generate Podcase Feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Podcast Generator
        uses: Navinchinnasamy/podcast-generator-action@main
